# model_runner.py
# Purpose: Send the prompt to two different AI models and return their responses.
#
# Think of this file as the "messenger":
#   - It takes the prompt text assembled by prompt_builder.py
#   - Sends it to OpenAI (Model A) and Anthropic (Model B)
#   - Returns what each model wrote back
#
# IMPORTANT: API keys must come from the .env file.
# They must NEVER be written directly in this code.

import os                     # os lets us read environment variables (API keys)
from dotenv import load_dotenv  # load_dotenv reads your .env file automatically

# Load the .env file so os.getenv() can find our API keys
load_dotenv()


# ── Model A: OpenAI ──────────────────────────────────────────────────────────

def run_openai_model(prompt: str, model_name: str = "gpt-4o-mini") -> str:
    """
    Send a prompt to an OpenAI model and return the response text.

    In plain English:
        - We pick up our OpenAI key from the .env file
        - We open a connection to OpenAI
        - We send the prompt as a "user" message (like typing in ChatGPT)
        - We wait for the response and return just the text

    Parameters
    ----------
    prompt : str
        The full prompt string built by prompt_builder.py.
    model_name : str
        Which OpenAI model to use. Default is "gpt-4o-mini" (fast and cheap).
        You can also pass "gpt-4o" for a more powerful (but more expensive) model.

    Returns
    -------
    str
        The morning note text generated by the model.

    Raises
    ------
    ValueError
        If OPENAI_API_KEY is not set in the .env file.

    Example
    -------
    >>> note = run_openai_model(prompt)
    >>> print(note[:200])
    """
    # Step 1: Read the API key from the .env file
    # If the key is missing, stop immediately with a clear error message
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError(
            "OPENAI_API_KEY is not set.\n"
            "Add it to your .env file:  OPENAI_API_KEY=sk-..."
        )

    # Step 2: Import the OpenAI library and create a client
    # The client is like opening a phone line to OpenAI
    from openai import OpenAI
    client = OpenAI(api_key=api_key)

    # Step 3: Send the prompt to the model
    # "messages" works like a chat — we send one message with role="user"
    # (just like typing into ChatGPT yourself)
    # temperature=0.3 means "be mostly consistent, a little creative"
    #   0.0 = very deterministic (same answer every time)
    #   1.0 = very creative (different answer every time)
    response = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,
    )

    # Step 4: Pull the text out of the response object and return it
    # response.choices[0] = the first (and only) reply
    # .message.content    = the actual text the model wrote
    return response.choices[0].message.content


# ── Model B: Anthropic Claude ────────────────────────────────────────────────

def run_anthropic_model(prompt: str, model_name: str = "claude-haiku-4-5-20251001") -> str:
    """
    Send a prompt to an Anthropic Claude model and return the response text.

    In plain English:
        - We pick up our Anthropic key from the .env file
        - We open a connection to Anthropic
        - We send the prompt and wait for Claude's response
        - We return just the text

    Parameters
    ----------
    prompt : str
        The full prompt string built by prompt_builder.py.
        Must be the SAME prompt used for OpenAI so the comparison is fair.
    model_name : str
        Which Claude model to use.
        "claude-haiku-4-5-20251001" = fast and cheap (good for demos)
        "claude-sonnet-4-6"         = more powerful (better quality)

    Returns
    -------
    str
        The morning note text generated by Claude.

    Raises
    ------
    ValueError
        If ANTHROPIC_API_KEY is not set in the .env file.

    Example
    -------
    >>> note = run_anthropic_model(prompt)
    >>> print(note[:200])
    """
    # Step 1: Read the API key from the .env file
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError(
            "ANTHROPIC_API_KEY is not set.\n"
            "Add it to your .env file:  ANTHROPIC_API_KEY=sk-ant-..."
        )

    # Step 2: Import the Anthropic library and create a client
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    # Step 3: Send the prompt to Claude
    # Anthropic's API is slightly different from OpenAI:
    #   - max_tokens: we must tell Claude the maximum reply length
    #     1024 tokens ≈ about 750 words, enough for a morning note
    #   - messages: same idea as OpenAI — one user message with our prompt
    message = client.messages.create(
        model=model_name,
        max_tokens=1024,
        messages=[
            {"role": "user", "content": prompt}
        ],
    )

    # Step 4: Pull the text out of the response object and return it
    # message.content is a list of content blocks; [0].text is the actual text
    return message.content[0].text


# ── Helper: save output to a file ───────────────────────────────────────────

def save_note(text: str, filepath: str) -> None:
    """
    Save a generated morning note to a file in the outputs/ folder.

    In plain English:
        Just writes the text to a .md file so you can read it later
        and compare the two models side by side.

    Parameters
    ----------
    text : str
        The morning note text returned by run_openai_model() or run_anthropic_model().
    filepath : str
        Where to save it (e.g., "outputs/model_a_morning_note.md").

    Example
    -------
    >>> save_note(model_a_output, "outputs/model_a_morning_note.md")
    """
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[model_runner] Saved note to {filepath}")
